### ISSUE TITLE
强烈感谢

### ISSUE THREAD

**Issue by anymoreT** [ningyu1/jmeter-plugins-dubbo#1]
我们公司现在测试Dubbo服务，也是封装的javaSample.
正在考虑怎么进一步优化，无意间看到你的项目，瞬间觉得世界美好了！
特别感谢，希望该项目能长期维护下去！

**Comment by ningyu1** [comment]
记得有问题及时反馈给我或者提PR都可以

**Comment by ningyu1** [comment]
@anymoreT 记得有问题及时反馈给我或者提PR都可以

**Comment by anymoreT** [comment]
好的。
