### ISSUE TITLE
请问GUI怎么调试呢？

### ISSUE THREAD

**Issue by anymoreT** [ningyu1/jmeter-plugins-dubbo#2]
你好，我下载了你的代码，由于项目的一些特殊需求，要在界面上再添加一些输入框。每次通过编译jar再放到jmeter的ext下面，感觉效率非常慢，也不能进行debug.
请问你是怎么进行界面调试的？

**Comment by ningyu1** [comment]
通过java的远程调试方式，或者下载jmeter源码然后调试，远程调试简单一些，你们要问家哪些参数？

**Comment by anymoreT** [comment]
我下载了jmeter源码进行调试好了gui,发现如果想要把dubbo集成进去调式，需要将dubbo相关的jar都集成进去，jmeter使用的是ant,怎么和maven集成的，还没有搞明白。
请问你说的java远程调试是怎么调式的呢？能稍微说细致点吗？

**Comment by anymoreT** [comment]
另外，你项目里面的pom应用了很多本地包，都没有上传呢。我使用maven包代替了。

**Comment by anymoreT** [comment]
<dependency>
			<groupId>avalon-framework</groupId>
			<artifactId>avalon-framework</artifactId>
			<version>4.1.5</version>
		</dependency>
		
		<dependency>
			<groupId>org.apache.jmeter</groupId>
			<artifactId>ApacheJMeter_core</artifactId>
			<version>3.1</version>
		</dependency>
		
		<dependency>
			<groupId>org.apache.avalon.logkit</groupId>
			<artifactId>avalon-logkit</artifactId>
			<version>2.2.1</version>
		</dependency>
		
		
		<dependency>
			<groupId>org.apache.jmeter</groupId>
			<artifactId>jorphan</artifactId>
			<version>3.1</version>
		</dependency>
		
		<dependency>
			<groupId>com.alibaba</groupId>
			<artifactId>dubbo</artifactId>
			<version>2.5.3</version>
			<exclusions>
				<exclusion>
					<groupId>org.springframework</groupId>
					<artifactId>spring</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		
		<dependency>
			<groupId>org.apache.zookeeper</groupId>
			<artifactId>zookeeper</artifactId>
			<version>3.4.6</version>
		</dependency>
		<dependency>
            <groupId>com.101tec</groupId>
            <artifactId>zkclient</artifactId>
            <version>0.2</version>
        </dependency>
		<dependency>
            <groupId>org.apache.curator</groupId>
            <artifactId>curator-framework</artifactId>
            <version>2.12.0</version>
        </dependency>
        <dependency>
            <groupId>de.ruedigermoeller</groupId>
            <artifactId>fst</artifactId>
            <version>2.48-jdk-6</version>
        </dependency>
		
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>1.7.5</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>log4j-over-slf4j</artifactId>
			<version>1.7.5</version>
		</dependency>
		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
			<version>2.8.2</version>
		</dependency>
		<dependency>
			<groupId>com.alibaba</groupId>
			<artifactId>fastjson</artifactId>
			<version>1.2.41</version>
		</dependency>

**Comment by ningyu1** [comment]
用jmeter源码来直接调试可以的。

在 2018-04-26 10:00:34，"anyMore" <notifications@github.com> 写道：


我下载了jmeter源码进行调试好了gui,发现如果想要把dubbo集成进去调式，需要将dubbo相关的jar都集成进去，jmeter使用的是ant,怎么和maven集成的，还没有搞明白。
请问你说的java远程调试是怎么调式的呢？能稍微说细致点吗？

**Comment by ningyu1** [comment]
@anymoreT 你看一下新版本，我把能加的参数都加上去了，或许你可以直接用不需要修改了

**Comment by anymoreT** [comment]
好的。你项目的pom.xml引用了很多本地包，你是否考虑把它换成maven仓库的包呢？我在本地已经都替换成maven仓库包了。另外对于接口的参数，是否可以再添加一列，作为参数名输入呢？我已经根据公司的要求，根据你的项目代码，进行了一些修改，已经可以使用了。

**Comment by anymoreT** [comment]
另外，如果考虑将该项目作为一个非常正规的项目维护，我建议将包路径里面的tsoft,tesing这些去掉。后续我也尝试根据实际需求，提交一些commit.

**Comment by ningyu1** [comment]
@anymoreT 过段时间会迁移到dubbo group下，所以会统一做一次修改
