### ISSUE TITLE
调用dubbo http协议的服务问题

### ISSUE THREAD

**Issue by zhangzc0419** [ningyu1/jmeter-plugins-dubbo#4]
我的dubbo服务改成http协议之后，调用遇到些问题
因为不是dubbo协议所以Server Setting没用dubbo的直连方式
Server Setting使用zookeeper协议
异常信息：
{"detailMessage":null,"stackTrace":[{"declaringClass":"cn.tsoft.framework.testing.jmeter.plugin.dubbo.sample.DubboSample","methodName":"callDubbo","fileName":"DubboSample.java","lineNumber":355},{"declaringClass":"cn.tsoft.framework.testing.jmeter.plugin.dubbo.sample.DubboSample","methodName":"sample","fileName":"DubboSample.java","lineNumber":234},{"declaringClass":"org.apache.jmeter.threads.JMeterThread","methodName":"executeSamplePackage","fileName":"JMeterThread.java","lineNumber":498},{"declaringClass":"org.apache.jmeter.threads.JMeterThread","methodName":"processSampler","fileName":"JMeterThread.java","lineNumber":424},{"declaringClass":"org.apache.jmeter.threads.JMeterThread","methodName":"run","fileName":"JMeterThread.java","lineNumber":255},{"declaringClass":"java.lang.Thread","methodName":"run","fileName":null,"lineNumber":-1}],"suppressedExceptions":[]}

**Comment by zhangzc0419** [comment]
1.2.6  
结果树完整的信息就是上面这个
没有调到实际的服务
dubbo服务端使用的http协议
server settings如下示意:
Protocol:Zookeeper@注册中心
Address:127.0.0.1:2181

**Comment by ningyu1** [comment]
@zhangzc0419 如果你们启用的http协议后，访问方式是通过http://ip:port/contextpath/${path}[/${method}][/${version}][/${group}]这种的话，请直接使用jmeter的http sample去做测试，dubbo sample就不适合使用。dubbo http协议支持的有些问题，不太清楚你们是通过那种方式开启的http协议？是用的dubbox还是dubbo-plus或者是其他

**Comment by zhangzc0419** [comment]
<dubbo:protocol name="http" port="8080" />
是dubbo内置的这种
http://dubbo.apache.org/books/dubbo-user-book/references/protocol/http.html

**Comment by ningyu1** [comment]
@zhangzc0419 issue连接：https://github.com/apache/incubator-dubbo/issues/1768

**Comment by zhangzc0419** [comment]
OK thx
