### ISSUE TITLE
怎么没有参数名的？那多个参数，怎么一一识别啊？

### ISSUE THREAD

**Issue by baoshd** [ningyu1/jmeter-plugins-dubbo#5]
怎么没有参数名的？那多个参数，怎么一一识别啊？

**Comment by ningyu1** [comment]
@baoshd 参数按照顺序在参数列表中添加，第一列是参数类型，第二列是参数值，具体参数对照表可以参考：

![image](https://user-images.githubusercontent.com/3387548/37324055-495fbb50-26c2-11e8-9bfa-3fb0739a5cf6.png)

**Comment by baoshd** [comment]
@ningyu1 我的意思是：如下面是两个参数，而且paramType 一样，他会不会把A的值付给B，B的值付给A
A  String   00246bc5f77447b7a3830dcd2312cdab
B  String   item:3781105002

**Comment by ningyu1** [comment]
@baoshd 不会的，是按照顺序赋值

**Comment by baoshd** [comment]
@ningyu1 嗯！建议：最好是把参数名也放出来

**Comment by ningyu1** [comment]
@baoshd 恩，你可以了解一下dubbo的generic调用方式（泛化调用），就知道为什么没有参数名了
http://dubbo.apache.org/books/dubbo-user-book/demos/generic-reference.html
